Repository LinkNacional/fraud-detection-for-woocommerce, pull requests merged in 2025-07, with the labels that each got.

#19 1.1.2 Alteração do título do plugin
  .github/workflows/main.yml
  CHANGELOG.md
  README.txt
  fraud-detection-for-woocommerce-file.php
  fraud-detection-for-woocommerce.php
  languages/fraud-detection-for-woocommerce-pt_BR.mo
  languages/fraud-detection-for-woocommerce-pt_BR.po
Labels: enhancement

#20 1.1.2 Alteração do título do plugin
  .github/workflows/main.yml
Labels: documentation

#21 1.1.2 Alteração do título do plugin
  .github/workflows/main.yml
Labels: bug
